import { ConditionKey, VitalSource, VitalType } from './shared';
import { ScreenKey, WidgetType } from './ui-config';
import { ConditionConfig } from '../types/ui-config';

export const ONCOLOGY_CONFIG: ConditionConfig = {
  conditionKey: ConditionKey.Oncology,
  displayName: 'Cancer Care Companion',
  shortName: 'Oncology',
  version: '1.0.0',
  theme: {
    primaryColor: '#E24B4A',
    accentColor: '#F09595',
    conditionIcon: 'ti-dna',
  },
  navigation: [
    { key: ScreenKey.Dashboard,     label: 'Home',         icon: 'ti-home' },
    { key: ScreenKey.ChemoSessions, label: 'Sessions',     icon: 'ti-flask', badge: 'dot' },
    { key: ScreenKey.SideEffects,   label: 'Side effects', icon: 'ti-activity' },
    { key: ScreenKey.LabResults,    label: 'Labs',         icon: 'ti-microscope' },
    { key: ScreenKey.Medications,   label: 'Medications',  icon: 'ti-pill' },
    { key: ScreenKey.Appointments,  label: 'Appointments', icon: 'ti-calendar' },
    { key: ScreenKey.AiChat,        label: 'Ask AI',       icon: 'ti-message-chatbot' },
    { key: ScreenKey.Education,     label: 'Learn',        icon: 'ti-book' },
    { key: ScreenKey.Reports,       label: 'Reports',      icon: 'ti-file-description' },
  ],
  dashboard: {
    primaryWidgets: [
      WidgetType.NextSessionCard,
      WidgetType.SideEffectSummary,
      WidgetType.MedicationTracker,
      WidgetType.LabResultCard,
    ],
    secondaryWidgets: [WidgetType.AppointmentCard, WidgetType.AiChatShortcut],
    quickActions: ['log_side_effect', 'view_next_session', 'ask_ai'],
  },
  vitals: [
    {
      type: VitalType.Weight,
      label: 'Weight',
      unit: 'kg',
      normalRange: { min: 40, max: 200, unit: 'kg' },
      trackingFrequency: { times: 1, period: 'week', asNeeded: false },
      source: [VitalSource.Manual, VitalSource.Healthkit],
      showTrendChart: true,
      alertEnabled: false,
    },
    {
      type: VitalType.Temperature,
      label: 'Temperature',
      unit: '°C',
      normalRange: { min: 36.1, max: 37.5, criticalMin: 35, criticalMax: 38.5, unit: '°C' },
      trackingFrequency: { times: 1, period: 'day', asNeeded: true },
      source: [VitalSource.Manual],
      showTrendChart: false,
      alertEnabled: true,
    },
  ],
  symptoms: [
    { code: 'nausea',     label: 'Nausea',       category: 'GI',      hasBodyMap: false, severityScale: '0-10' },
    { code: 'fatigue',    label: 'Fatigue',       category: 'General', hasBodyMap: false, severityScale: '0-10' },
    { code: 'pain',       label: 'Pain',          category: 'Pain',    hasBodyMap: true,  severityScale: '0-10' },
    { code: 'neuropathy', label: 'Tingling/Numb', category: 'Neuro',   hasBodyMap: true,  severityScale: '0-10' },
    { code: 'mucositis',  label: 'Mouth sores',   category: 'Oral',    hasBodyMap: false, severityScale: '0-10' },
    { code: 'hair_loss',  label: 'Hair loss',     category: 'Skin',    hasBodyMap: false, severityScale: '1-5' },
    { code: 'appetite',   label: 'Appetite loss', category: 'GI',      hasBodyMap: false, severityScale: '0-10' },
    { code: 'vomiting',   label: 'Vomiting',      category: 'GI',      hasBodyMap: false, severityScale: '0-10' },
  ],
  reminders: [
    { type: 'medication',  defaultTimes: ['08:00', '20:00'], canUserCustomize: true,  pushEnabled: true, localFallback: true },
    { type: 'appointment', defaultTimes: ['09:00'],          canUserCustomize: false, pushEnabled: true, localFallback: true },
    { type: 'log_entry',   defaultTimes: ['21:00'],          canUserCustomize: true,  pushEnabled: true, localFallback: true },
  ],
  education: [
    { id: 'chemo_basics',     title: 'Understanding chemotherapy',   description: 'What to expect during treatment', contentType: 'article',     tags: ['chemo', 'basics'],    estimatedMinutes: 8,  requiredForOnboarding: true },
    { id: 'side_effects_101', title: 'Managing common side effects', description: 'Nausea, fatigue, and more',       contentType: 'video',       tags: ['side effects'],       estimatedMinutes: 12, requiredForOnboarding: true },
    { id: 'nutrition_cancer', title: 'Nutrition during cancer care', description: 'Eating well during treatment',    contentType: 'article',     tags: ['nutrition'],          estimatedMinutes: 6,  requiredForOnboarding: false },
    { id: 'clinical_trials',  title: 'Clinical trials explained',    description: 'Is a trial right for you?',       contentType: 'infographic', tags: ['trials', 'research'], estimatedMinutes: 4,  requiredForOnboarding: false },
  ],
  onboardingSteps: [
    { id: 'cancer_type',     title: 'Your diagnosis',      description: 'Tell us about your cancer type and stage', screenKey: ScreenKey.Dashboard,     required: true,  order: 1 },
    { id: 'care_team',       title: 'Your care team',      description: 'Add your oncologist details',               screenKey: ScreenKey.Appointments,   required: true,  order: 2 },
    { id: 'first_session',   title: 'Next chemo session',  description: 'Schedule your first session',               screenKey: ScreenKey.ChemoSessions,  required: false, order: 3 },
    { id: 'medications',     title: 'Current medications', description: 'Add your medications',                      screenKey: ScreenKey.Medications,    required: false, order: 4 },
    { id: 'education_start', title: 'Learn the basics',    description: 'Complete your first learning module',       screenKey: ScreenKey.Education,      required: true,  order: 5 },
  ],
  aiAssistant: {
    systemPromptAddendum: 'You are a compassionate oncology support assistant. The patient is undergoing cancer treatment. Focus on symptom management, medication adherence, and emotional support. Always recommend consulting their oncologist for clinical decisions. Be sensitive to their emotional state.',
    suggestedQuestions: [
      'How can I manage nausea after chemo?',
      'What foods are safe to eat during treatment?',
      'When should I call my oncologist immediately?',
      'How do I track my side effects?',
      'What is a clinical trial?',
    ],
    restrictedTopics: ['specific drug dosing', 'diagnosis interpretation', 'prognosis prediction'],
    triageEnabled: true,
    escalationKeywords: ['fever', 'temperature above 38', 'severe pain', 'bleeding', 'difficulty breathing', 'chest pain'],
  },
  report: {
    sections: ['profile', 'chemo_sessions', 'side_effects', 'medications', 'lab_results', 'vitals'],
    includeVitals: true,
    includeSymptoms: true,
    includeMedications: true,
    includeLabResults: true,
    exportFormat: ['pdf', 'json'],
    shareWithProvider: true,
  },
  featureFlags: {
    clinicalTrialMatching: true,
    caregiverAccess: true,
    labResultPush: true,
    ctcaeGrading: true,
    offlineSymptomLog: true,
    telehealth: false,
  },
  updatedAt: '2025-05-28T00:00:00Z',
};


export const DIABETES_CONFIG: ConditionConfig = {
  conditionKey: ConditionKey.Diabetes,
  displayName: 'Diabetes Care Manager',
  shortName: 'Diabetes',
  version: '1.0.0',
  theme: {
    primaryColor: '#EF9F27',
    accentColor: '#FAC775',
    conditionIcon: 'ti-droplet',
  },
  navigation: [
    { key: ScreenKey.Dashboard,      label: 'Home',         icon: 'ti-home' },
    { key: ScreenKey.GlucoseTracker, label: 'Glucose',      icon: 'ti-chart-line', badge: 'dot' },
    { key: ScreenKey.InsulinLog,     label: 'Insulin',      icon: 'ti-needle' },
    { key: ScreenKey.MealLog,        label: 'Meals',        icon: 'ti-salad' },
    { key: ScreenKey.Medications,    label: 'Medications',  icon: 'ti-pill' },
    { key: ScreenKey.Appointments,   label: 'Appointments', icon: 'ti-calendar' },
    { key: ScreenKey.Vitals,         label: 'Vitals',       icon: 'ti-heart-rate-monitor' },
    { key: ScreenKey.AiChat,         label: 'Ask AI',       icon: 'ti-message-chatbot' },
    { key: ScreenKey.Reports,        label: 'Reports',      icon: 'ti-file-description' },
  ],
  dashboard: {
    primaryWidgets: [
      WidgetType.GlucoseTrend,
      WidgetType.MedicationTracker,
      WidgetType.VitalsChart,
      WidgetType.AppointmentCard,
    ],
    secondaryWidgets: [WidgetType.AiChatShortcut, WidgetType.SymptomLog],
    quickActions: ['log_glucose', 'log_insulin', 'log_meal'],
  },
  vitals: [
    {
      type: VitalType.Glucose,
      label: 'Blood glucose',
      unit: 'mg/dL',
      normalRange: { min: 80, max: 180, criticalMin: 54, criticalMax: 250, unit: 'mg/dL' },
      trackingFrequency: { times: 4, period: 'day', asNeeded: true },
      source: [VitalSource.Manual, VitalSource.Cgm, VitalSource.Healthkit],
      showTrendChart: true,
      alertEnabled: true,
    },
    {
      type: VitalType.Hba1c,
      label: 'HbA1c',
      unit: '%',
      normalRange: { min: 4.0, max: 7.0, criticalMax: 9.0, unit: '%' },
      trackingFrequency: { times: 1, period: 'month', asNeeded: false },
      source: [VitalSource.Manual],
      showTrendChart: true,
      alertEnabled: true,
    },
    {
      type: VitalType.BloodPressureSystolic,
      label: 'Blood pressure',
      unit: 'mmHg',
      normalRange: { min: 90, max: 130, criticalMax: 180, unit: 'mmHg' },
      trackingFrequency: { times: 1, period: 'day', asNeeded: false },
      source: [VitalSource.Manual, VitalSource.Healthkit],
      showTrendChart: true,
      alertEnabled: true,
    },
    {
      type: VitalType.Weight,
      label: 'Weight',
      unit: 'kg',
      normalRange: { min: 40, max: 250, unit: 'kg' },
      trackingFrequency: { times: 1, period: 'week', asNeeded: false },
      source: [VitalSource.Manual, VitalSource.Healthkit],
      showTrendChart: true,
      alertEnabled: false,
    },
  ],
  symptoms: [
    { code: 'hypoglycemia_feeling', label: 'Low blood sugar feeling', category: 'Glucose', hasBodyMap: false, severityScale: '0-10' },
    { code: 'excessive_thirst',     label: 'Excessive thirst',         category: 'General', hasBodyMap: false, severityScale: '0-10' },
    { code: 'frequent_urination',   label: 'Frequent urination',       category: 'General', hasBodyMap: false, severityScale: '1-5' },
    { code: 'blurry_vision',        label: 'Blurry vision',            category: 'Vision',  hasBodyMap: false, severityScale: '0-10' },
    { code: 'numbness_feet',        label: 'Numbness in feet',         category: 'Neuro',   hasBodyMap: true,  severityScale: '0-10' },
    { code: 'fatigue',              label: 'Fatigue',                  category: 'General', hasBodyMap: false, severityScale: '0-10' },
    { code: 'slow_healing',         label: 'Slow wound healing',       category: 'Skin',    hasBodyMap: true,  severityScale: '1-5' },
  ],
  reminders: [
    { type: 'medication',  defaultTimes: ['08:00', '20:00'],                   canUserCustomize: true,  pushEnabled: true, localFallback: true },
    { type: 'vitals',      defaultTimes: ['07:00', '12:00', '18:00', '22:00'], canUserCustomize: true,  pushEnabled: true, localFallback: true },
    { type: 'log_entry',   defaultTimes: ['07:00', '12:00', '18:00', '22:00'], canUserCustomize: true,  pushEnabled: true, localFallback: true },
    { type: 'appointment', defaultTimes: ['09:00'],                            canUserCustomize: false, pushEnabled: true, localFallback: true },
  ],
  education: [
    { id: 'understanding_glucose', title: 'Understanding blood glucose',  description: 'What numbers mean and why they matter', contentType: 'article',     tags: ['glucose', 'basics'],  estimatedMinutes: 7,  requiredForOnboarding: true },
    { id: 'carb_counting',         title: 'Carbohydrate counting',        description: 'How to count carbs for better control',  contentType: 'video',       tags: ['nutrition', 'carbs'], estimatedMinutes: 10, requiredForOnboarding: true },
    { id: 'insulin_guide',         title: 'Insulin basics',               description: 'Types, timing, and injection technique', contentType: 'article',     tags: ['insulin'],            estimatedMinutes: 8,  requiredForOnboarding: false },
    { id: 'hypoglycemia_action',   title: 'Hypoglycemia action plan',     description: 'What to do when glucose drops low',      contentType: 'infographic', tags: ['safety', 'hypo'],     estimatedMinutes: 3,  requiredForOnboarding: true },
    { id: 'cgm_setup',             title: 'Using a CGM device',           description: 'Getting the most from your sensor',      contentType: 'video',       tags: ['cgm', 'device'],      estimatedMinutes: 6,  requiredForOnboarding: false },
  ],
  onboardingSteps: [
    { id: 'diabetes_type',   title: 'Your diabetes type',    description: 'Tell us whether you have T1, T2, or other', screenKey: ScreenKey.Dashboard,      required: true,  order: 1 },
    { id: 'glucose_targets', title: 'Set glucose targets',   description: 'Enter your target glucose range',           screenKey: ScreenKey.GlucoseTracker, required: true,  order: 2 },
    { id: 'medications',     title: 'Current medications',   description: 'Add your diabetes medications',             screenKey: ScreenKey.Medications,    required: true,  order: 3 },
    { id: 'first_glucose',   title: 'Log your first glucose',description: 'Log your current blood glucose',           screenKey: ScreenKey.GlucoseTracker, required: false, order: 4 },
    { id: 'cgm_connect',     title: 'Connect your CGM',      description: 'Sync your continuous glucose monitor',     screenKey: ScreenKey.GlucoseTracker, required: false, order: 5 },
  ],
  aiAssistant: {
    systemPromptAddendum: 'You are a diabetes education and support assistant. Help the patient understand glucose patterns, carb counting, medication timing, and lifestyle management. Never recommend specific insulin doses. Always advise consulting their endocrinologist for treatment changes.',
    suggestedQuestions: [
      'Why is my glucose high after meals?',
      'How do I count carbohydrates?',
      'What should I do if my glucose drops low?',
      'How does exercise affect my blood sugar?',
      'What foods have a low glycemic index?',
    ],
    restrictedTopics: ['specific insulin dose recommendation', 'stopping medication', 'diagnosis of complications'],
    triageEnabled: true,
    escalationKeywords: ['glucose below 54', 'glucose above 350', 'passed out', 'seizure', "can't wake up", 'diabetic ketoacidosis', 'DKA'],
  },
  report: {
    sections: ['profile', 'glucose_summary', 'insulin_log', 'meal_log', 'medications', 'vitals', 'hba1c_trend'],
    includeVitals: true,
    includeSymptoms: true,
    includeMedications: true,
    includeLabResults: true,
    exportFormat: ['pdf', 'csv'],
    shareWithProvider: true,
  },
  featureFlags: {
    cgmIntegration: true,
    healthkitSync: true,
    healthConnectSync: true,
    mealPhotoLogging: true,
    carbCalculator: true,
    glucosePrediction: false,
    caregiverAccess: true,
    offlineGlucoseLog: true,
    a1cEstimator: true,
  },
  updatedAt: '2025-05-28T00:00:00Z',
};


export const OBESITY_GLP1_CONFIG: ConditionConfig = {
  conditionKey: ConditionKey.ObesityGlp1,
  displayName: 'Weight Care Program',
  shortName: 'Weight Care',
  version: '1.0.0',
  theme: {
    primaryColor: '#378ADD',
    accentColor: '#85B7EB',
    conditionIcon: 'ti-scale',
  },
  navigation: [
    { key: ScreenKey.Dashboard,    label: 'Home',         icon: 'ti-home' },
    { key: ScreenKey.WeightTracker,label: 'Weight',       icon: 'ti-trending-down', badge: 'dot' },
    { key: ScreenKey.InjectionLog, label: 'Injections',   icon: 'ti-syringe' },
    { key: ScreenKey.AppetiteLog,  label: 'Appetite',     icon: 'ti-apple' },
    { key: ScreenKey.Medications,  label: 'Medications',  icon: 'ti-pill' },
    { key: ScreenKey.Appointments, label: 'Appointments', icon: 'ti-calendar' },
    { key: ScreenKey.Vitals,       label: 'Vitals',       icon: 'ti-heart-rate-monitor' },
    { key: ScreenKey.AiChat,       label: 'Ask AI',       icon: 'ti-message-chatbot' },
    { key: ScreenKey.Education,    label: 'Learn',        icon: 'ti-book' },
  ],
  dashboard: {
    primaryWidgets: [
      WidgetType.WeightTrend,
      WidgetType.InjectionLog,
      WidgetType.MedicationTracker,
      WidgetType.VitalsChart,
    ],
    secondaryWidgets: [WidgetType.AppointmentCard, WidgetType.AiChatShortcut, WidgetType.SymptomLog],
    quickActions: ['log_weight', 'log_injection', 'log_appetite'],
  },
  vitals: [
    {
      type: VitalType.Weight,
      label: 'Weight',
      unit: 'kg',
      normalRange: { min: 40, max: 300, unit: 'kg' },
      trackingFrequency: { times: 1, period: 'week', asNeeded: false },
      source: [VitalSource.Manual, VitalSource.Healthkit, VitalSource.HealthConnect],
      showTrendChart: true,
      alertEnabled: false,
    },
    {
      type: VitalType.BloodPressureSystolic,
      label: 'Blood pressure',
      unit: 'mmHg',
      normalRange: { min: 90, max: 130, criticalMax: 180, unit: 'mmHg' },
      trackingFrequency: { times: 1, period: 'week', asNeeded: false },
      source: [VitalSource.Manual, VitalSource.Healthkit],
      showTrendChart: true,
      alertEnabled: true,
    },
    {
      type: VitalType.HeartRate,
      label: 'Heart rate',
      unit: 'bpm',
      normalRange: { min: 50, max: 100, criticalMin: 40, criticalMax: 130, unit: 'bpm' },
      trackingFrequency: { times: 1, period: 'day', asNeeded: true },
      source: [VitalSource.Healthkit, VitalSource.HealthConnect],
      showTrendChart: true,
      alertEnabled: true,
    },
  ],
  symptoms: [
    { code: 'nausea',         label: 'Nausea',                  category: 'GI',      hasBodyMap: false, severityScale: '0-10' },
    { code: 'vomiting',       label: 'Vomiting',                category: 'GI',      hasBodyMap: false, severityScale: '0-10' },
    { code: 'diarrhea',       label: 'Diarrhea',                category: 'GI',      hasBodyMap: false, severityScale: '0-10' },
    { code: 'constipation',   label: 'Constipation',            category: 'GI',      hasBodyMap: false, severityScale: '0-10' },
    { code: 'abdominal_pain', label: 'Abdominal pain',          category: 'GI',      hasBodyMap: true,  severityScale: '0-10' },
    { code: 'injection_site', label: 'Injection site reaction', category: 'Skin',    hasBodyMap: true,  severityScale: '0-10' },
    { code: 'headache',       label: 'Headache',                category: 'General', hasBodyMap: false, severityScale: '0-10' },
    { code: 'fatigue',        label: 'Fatigue',                 category: 'General', hasBodyMap: false, severityScale: '0-10' },
    { code: 'dizziness',      label: 'Dizziness',               category: 'General', hasBodyMap: false, severityScale: '0-10' },
  ],
  reminders: [
    { type: 'injection',   defaultTimes: ['09:00'], canUserCustomize: true,  pushEnabled: true, localFallback: true },
    { type: 'medication',  defaultTimes: ['08:00'], canUserCustomize: true,  pushEnabled: true, localFallback: true },
    { type: 'vitals',      defaultTimes: ['07:00'], canUserCustomize: true,  pushEnabled: true, localFallback: true },
    { type: 'log_entry',   defaultTimes: ['20:00'], canUserCustomize: true,  pushEnabled: true, localFallback: true },
    { type: 'appointment', defaultTimes: ['09:00'], canUserCustomize: false, pushEnabled: true, localFallback: true },
  ],
  education: [
    { id: 'how_glp1_works',      title: 'How GLP-1 medications work',    description: 'The science behind Ozempic and Mounjaro', contentType: 'video',       tags: ['glp1', 'basics'],      estimatedMinutes: 8,  requiredForOnboarding: true },
    { id: 'injection_technique', title: 'Injection technique guide',      description: 'Step-by-step injection instructions',     contentType: 'video',       tags: ['injection'],           estimatedMinutes: 5,  requiredForOnboarding: true },
    { id: 'managing_nausea',     title: 'Managing nausea and GI effects', description: 'Tips to reduce common side effects',      contentType: 'article',     tags: ['side effects', 'GI'],  estimatedMinutes: 6,  requiredForOnboarding: true },
    { id: 'nutrition_obesity',   title: 'Nutrition and calorie goals',    description: 'Eating well to support weight loss',      contentType: 'article',     tags: ['nutrition'],           estimatedMinutes: 7,  requiredForOnboarding: false },
    { id: 'titration_plan',      title: 'Understanding dose titration',   description: 'Why your dose increases over time',       contentType: 'infographic', tags: ['dosing', 'titration'], estimatedMinutes: 4,  requiredForOnboarding: true },
    { id: 'exercise_glp1',       title: 'Exercise and GLP-1 therapy',     description: 'Safe activity during your program',       contentType: 'article',     tags: ['exercise'],            estimatedMinutes: 6,  requiredForOnboarding: false },
  ],
  onboardingSteps: [
    { id: 'program_setup',      title: 'Your program',           description: 'Tell us your starting weight and goals',   screenKey: ScreenKey.WeightTracker, required: true,  order: 1 },
    { id: 'drug_selection',     title: 'Your GLP-1 medication',  description: 'Which medication has been prescribed?',    screenKey: ScreenKey.InjectionLog,  required: true,  order: 2 },
    { id: 'first_injection',    title: 'First injection log',    description: 'Log your first injection',                screenKey: ScreenKey.InjectionLog,  required: false, order: 3 },
    { id: 'weight_baseline',    title: 'Baseline weight',        description: 'Log your starting weight',                screenKey: ScreenKey.WeightTracker, required: true,  order: 4 },
    { id: 'injection_tutorial', title: 'Injection tutorial',     description: 'Watch the injection technique video',     screenKey: ScreenKey.Education,     required: true,  order: 5 },
  ],
  aiAssistant: {
    systemPromptAddendum: 'You are a supportive weight management and GLP-1 therapy assistant. Help the patient with injection technique, managing side effects (especially nausea and GI issues), nutrition, and lifestyle habits. Be encouraging and non-judgmental about weight. Never recommend dose changes — always direct them to their prescriber.',
    suggestedQuestions: [
      'How do I reduce nausea from my injection?',
      'What should I eat the day of my injection?',
      'How do I know if my dose needs adjusting?',
      'Why am I losing weight slower this week?',
      'Where are the best injection sites?',
    ],
    restrictedTopics: ['dose modification', 'stopping treatment without medical supervision', 'specific weight loss timelines as guarantees'],
    triageEnabled: true,
    escalationKeywords: ['severe abdominal pain', 'pancreatitis', 'persistent vomiting', 'gallbladder', 'thyroid lump', "can't keep food down", 'severe dizziness'],
  },
  report: {
    sections: ['profile', 'weight_trend', 'bmi_progress', 'injection_log', 'side_effects', 'vitals', 'medications'],
    includeVitals: true,
    includeSymptoms: true,
    includeMedications: true,
    includeLabResults: false,
    exportFormat: ['pdf'],
    shareWithProvider: true,
  },
  featureFlags: {
    weeklyProgressSummary: true,
    healthkitSync: true,
    healthConnectSync: true,
    photoBodyTracking: false,
    penLotTracking: true,
    caregiverAccess: false,
    offlineWeightLog: true,
    injectionSiteRotation: true,
    nutritionAiSuggestions: true,
    bmiCalculator: true,
  },
  updatedAt: '2025-05-28T00:00:00Z',
};


/** Config registry — load by condition key at runtime */
export const CONDITION_CONFIGS: Record<ConditionKey, ConditionConfig> = {
  [ConditionKey.Oncology]:    ONCOLOGY_CONFIG,
  [ConditionKey.Diabetes]:    DIABETES_CONFIG,
  [ConditionKey.ObesityGlp1]: OBESITY_GLP1_CONFIG,
};

/** Helper to get typed config at runtime */
export function getConditionConfig(key: ConditionKey): ConditionConfig {
  return CONDITION_CONFIGS[key];
}
